"""Public mission interfaces. Positions: cm, yaw: degrees clockwise, world Y right."""
from dataclasses import dataclass
from typing import Protocol


class ControlLost(RuntimeError):
    pass


class MissionError(RuntimeError):
    pass


@dataclass
class Observation:
    frame_id: str
    pose: dict
    epoch: str
    rgb: object
    jpeg_base64: str
    intrinsics: object
    world_from_camera_cm: object
    timestamp_s: float


class Robot(Protocol):
    def attach(self): ...
    def health(self): ...
    def pose(self): ...
    def wait_stopped(self): ...
    def observe(self) -> Observation: ...
    def preview_path(self, goal, require_arrival=False): ...
    def locate_target(self, observation, mask): ...
    def point_is_free(self, pose): ...
    def navigate(self, pose): ...
    def stop(self): ...
    def land(self): ...
    def close(self): ...
