cmake_minimum_required(VERSION 3.0.2)
project(owl_nav_v22)
find_package(catkin REQUIRED COMPONENTS rospy std_msgs geometry_msgs traj_utils message_generation)
catkin_python_setup()
add_message_files(FILES PlannerTrajectory.msg)
add_service_files(FILES Command.srv Plan.srv)
generate_messages(DEPENDENCIES std_msgs geometry_msgs traj_utils)
catkin_package(CATKIN_DEPENDS message_runtime rospy std_msgs geometry_msgs traj_utils)
catkin_install_python(PROGRAMS scripts/owl_nav_v22_node.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
install(DIRECTORY launch DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION})
